# Generated by Django 4.0.2 on 2023-11-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitzapp', '0002_rename_name_user_registration_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='address',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='user_registration',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='lastname',
        ),
    ]
