# Generated by Django 4.0.2 on 2023-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitzapp', '0003_rename_address_user_registration_addres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
