# Generated by Django 4.0.2 on 2023-11-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glitzapp', '0004_user_registration_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('posting_date', models.DateField()),
                ('cover_image', models.ImageField(default='static/images/logo/icon.png', upload_to='images/cover')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='event_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=255)),
                ('link', models.TextField(blank=True, null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.events_table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='event_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/images/logo/icon.png', upload_to='images/album')),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.events_table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='event_empeded_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empeded_link', models.TextField(blank=True, null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.events_table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glitzapp.user_registration')),
            ],
        ),
    ]
