# Generated by Django 4.0.2 on 2023-11-15 04:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glitzapp', '0008_alter_event_empeded_link_empeded_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_empeded_link',
            name='empeded_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
